advanced/conditions.md, api-reference/selectors.md
Addresses https://github.com/mobile-dev-inc/maestro/pull/999#issuecomment-1523175070
=> Add docs for `containsDescendants` selector

advanced/conditions.md, advanced/javascript/README.md, advanced/javascript/logging.md, advanced/javascript/make-http-s-requests.md
Added an example of a common request series to the http docs, as we found that the syntax required was quite particular, particularly when chaining requests. 
Added an example of applying multiple conditions. 
Minor suggested edits to logging section.
Edits/feedback very welcome.
=> Minor updates to http, conditional, and logging docs.

community/contributions.md
As per mentioned in this [Slack's thread](https://mobile-dev-inc.slack.com/archives/C041FU72T54/p1679442248224939)
=> Adds asdf-plugin as a community contribution

api-reference/commands/runflow.md
Update runFlow env documentation to correct syntax
=> Update runFlow env documentation to correct syntax

getting-started/maestro-studio.md
Primarily fixes the `wit` -> `with` typo, but improves readability of a few other sentences too.
=> Minor typographic improvements

advanced/javascript/make-http-s-requests.md
Related to https://github.com/mobile-dev-inc/maestro/pull/1474
=> Add information about multipart form data

api-reference/commands/presskey.md
Updated Documentation to reflect new Android TV controls
https://github.com/mobile-dev-inc/maestro/pull/1659
=> Update presskey.md for Android TV remote controls

getting-started/installing-maestro/README.md
Installing from a dockerfile required me to parse through the bash install script, so I figured I'd add some docs for it
=> Add instructions for installing in a Dockerfile

getting-started/installing-maestro/windows.md
While setting this up on Windows we found that using openjdk-11 provides too old version of Java (LinkageError...)
=> docs: Update windows.md with correct version of Java

advanced/detect-maestro-in-your-app.md, api-reference/commands/launchapp.md, troubleshooting/frequently-asked-questions.md, troubleshooting/known-issues.md
Spent some time in Slack. Answers to some common or interesting queries added to the docs.
=> Contribute solutions to some common questions

api-reference/labels.md
Some additional context and examples
=> Improve docs for labels

api-reference/commands/inputtext.md
Adding length info for inputText
=> Update inputText Documentation

api-reference/commands/tapon.md
=> Added retryIfNoChange to tapon.md

advanced/javascript/run-javascript.md
⚠️ Merge after https://github.com/mobile-dev-inc/maestro/pull/1747
Needed docs for maestro.platform
Documented the other JS internals whilst I was there :)
=> [merge with next maestro release] Add docs for inbuilt JavaScript functions and properties

cli/test-suites-and-reports.md
https://github.com/mobile-dev-inc/maestro/pull/1750 
- add new test report format: html
- add test report example
@axelniklasson
=> [merge with next maestro release] add new test report format: html

api-reference/commands/setairplanemode.md, api-reference/commands/toggleairplanemode.md
document features added in https://github.com/mobile-dev-inc/maestro/pull/1672
=> [merge with next maestro release] document setAirplaneMode and toggleAirplaneMode

SUMMARY.md, api-reference/commands/killapp.md
Adds documentation for the new `killApp` command which was recently merged into Maestro.
PR https://github.com/mobile-dev-inc/maestro/pull/1727
=> [merge with next maestro release] Add killApp Documentation

api-reference/configuration/workspace-configuration.md, cli/test-suites-and-reports.md
it's been deprecated for a long time now
=> Remove all mentions of deterministic order

api-reference/commands/takescreenshot.md
uno reverse: fix (a possible) bug by changing docs :D
fix https://github.com/mobile-dev-inc/maestro/issues/1911
=> Update `takeScreenshot` docs to reflect reality

api-reference/commands/clearstate.md, getting-started/installing-maestro/README.md, troubleshooting/bug-report.md
- **remove mentions of idb**
- **remove mentions of idb v2**
=> remove idb mentions

troubleshooting/known-issues.md
[See #565 in Maestro repo](https://github.com/mobile-dev-inc/maestro/issues/565)
=> Remove mention of iOS landscape mode not being supported

examples/facebook-signup-flow-automation.md
=> chore: update docs to use correct command

community/resources.md
cc. @Fishbowler  @felipeduartea
=> Add awesome-maestro to official resources

getting-started/maestro-mcp.md
=> add link to JetBrains IDEs docs in Maestro MCP docs

advanced/javascript/generating-random-with-faker.md, api-reference/commands/inputtext.md
Docs to accompany https://github.com/mobile-dev-inc/Maestro/pull/2341
=> Add Faker docs
